### ISSUE TITLE
namespace 设计

### ISSUE THREAD

**Issue by heimanba** [devsapp/sae#27]
现在设计为
```
namespace: #  选填
        id: cn-beijing:test
        name: test-name
        description: namespace desc
```
namespace 不会存在创建的场景，因为这里需要和vpc/vswitchId 配合，所以namespace只能是导入。这里是否可以设计为
```
namespaceId: cn-beijing:test
```
![image](https://user-images.githubusercontent.com/5129967/183542909-9ae4e83a-53d8-4cfd-82fe-799d270a7eaa.png)

**Comment by heimanba** [comment]
![image](https://user-images.githubusercontent.com/5129967/183546448-320d4452-0550-49f3-b18e-07b55168a4cb.png)


namespaceId以及vpcConfig都是成对出现的，所以，是否这样设计

```
application:
        appName: "start-sae-php" 
        namespaceId: cn-hangzhou:dankun
        vpcId: vpc-bp1luoui6j7a0doju6l13
        vSwitchId: vsw-bp15pcrj9rp5jtusyq6ju
        securityGroupId: sg-bp15usvhukzpqfleotfp

        code:
          packageType: PhpZip
          packageVersion: 0.0.1
          packageUrl: hello-sae-php.zip / https://sae-packages-cn-hangzhou-1976152945975242.oss-cn-hangzhou.aliyuncs.com/Ogjfx1yYEijpiAil.zip
          ossConfig: auto | cn-tracker-admin/serverless-devs/app-center
          imageUrl: xxxxx
        port: 80
```



```
ossConfig: auto  | cn-tracker-admin/serverless-devs/app-center
```
