### ISSUE TITLE
slbConfig参数

### ISSUE THREAD

**Issue by heimanba** [devsapp/sae#34]
```
services:
  sae-test: #  服务名称
    component:  devsapp/sae
    props:
      application:
        region: cn-beijing
        port: 8080
      slbConfig: auto
```

1. auto: 
-  公网访问地址
- 使用是HTTP协议，并且HTTP端口为80

2. 用户自己填写
