### ISSUE TITLE
希望可以支持Jar和Dockerfile的模式

### ISSUE THREAD

**Issue by anycodes** [devsapp/sae#5]
```
edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: sae-app            #  项目名称
access: aliyun-release  #  秘钥别名

services:
  sae-test: #  服务名称
    component:  devsapp/sae
    props:
      region: cn-shenzhen
      appName: dankun-sae
      appDescription: saedemo
      code:
        imageUrl: registry-vpc.cn-shenzhen.aliyuncs.com/sae-demo-image/consumer:1.0
        path: 可以是.jar, war
        image: xxx /指定本地镜像
      replicas: 1
      cpu: 500
      memory: 1024
      port: 80
      targetPort: 8080
```

关于docker image push到acr，可以参考：https://github.com/devsapp/fc-deploy/blob/e52ce40dcaf2e44f0ab14433272aa7fcc4beafbf/src/lib/fc/function.ts#L291
