### ISSUE TITLE
SAE 新版设计

### ISSUE THREAD

**Issue by heimanba** [devsapp/sae#8]
## s.yaml设计

```
region: cn-hangzhou
name: test
description: This is a test description
namespace: # 选填
  id: cn-beijing:test
  name: name
  description: namespace desc
vpcConfig: # 选填
  vpcId: xx
  vSwitchId: xx
  securityGroupId: xxx
package: 
  javaWar/javaJar/javaImage
  phpZip/phpImage
  image
cpu: 500(默认)
memory: 1024(默认)
replicas: 1

slb: 
  type: Intranet
    id: lb-bp1tg0k6d9nqaw7l1****
    config:
      - port: 80
        targetPort: 8080
        protocol: TCP
     
```

#### javaWar
```
type: FatJar
version: 0.0.1
url: xxxx
jdk: xxx
```
